version: '3.8'

services:
  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    container_name: mysql-services
    environment:
      MYSQL_ROOT_PASSWORD: aserttdsdcgrfswfszf
      TZ: Asia/Shanghai
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  python-app:
    build: .
    entrypoint: /app/start.sh
    depends_on:
      mysql:
        condition: service_healthy
    container_name: python-app
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  mysql-data:
