"""add task status and assignment fields to care table

Revision ID: 476ffa8cb0e7
Revises: 4c331c81f777
Create Date: 2025-04-27 15:55:19.941950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '476ffa8cb0e7'
down_revision: Union[str, None] = '4c331c81f777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care', sa.Column('status', sa.Enum('待接取', '已接取', '已完成'), server_default='待接取', nullable=False))
    op.add_column('care', sa.Column('assign_type', sa.Enum('自主接取', '强制分配'), nullable=True))
    op.add_column('care', sa.Column('assign_time', sa.DateTime(), nullable=True))
    op.alter_column('care', 'caregiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('care', 'caregiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('care', 'assign_time')
    op.drop_column('care', 'assign_type')
    op.drop_column('care', 'status')
    # ### end Alembic commands ###
