"""update care_plan table

Revision ID: 4c331c81f777
Revises: 346c55e44a54
Create Date: 2025-04-27 14:26:57.047400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c331c81f777'
down_revision: Union[str, None] = '346c55e44a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care_plan', sa.Column('plan_name', sa.String(length=100), nullable=False))
    op.alter_column('care_plan', 'status',
                   existing_type=sa.Enum('未完成', '已完成', name='status_enum'),
                   type_=sa.Enum('进行中', '已结束', '暂停', name='status_enum'),
                   existing_nullable=False,
                   server_default='进行中')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('care_plan', 'plan_name')
    # ### end Alembic commands ###
