"""update care and care_plan tables

Revision ID: 6a60e79fe819
Revises: 476ffa8cb0e7
Create Date: 2025-04-27 17:23:31.874563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a60e79fe819'
down_revision: Union[str, None] = '476ffa8cb0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care', sa.Column('actual_time', sa.DateTime(), nullable=True))
    op.alter_column('care', 'caregiver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('care', 'assign_time')
    op.drop_column('care', 'status')
    op.drop_column('care', 'assign_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('care', sa.Column('assign_type', mysql.ENUM('自主接取', '强制分配'), nullable=True))
    op.add_column('care', sa.Column('status', mysql.ENUM('待接取', '已接取', '已完成'), server_default=sa.text("'待接取'"), nullable=False))
    op.add_column('care', sa.Column('assign_time', mysql.DATETIME(), nullable=True))
    op.alter_column('care', 'caregiver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('care', 'actual_time')
    # ### end Alembic commands ###
